### ISSUE TITLE
Missing .jar file?

### ISSUE THREAD

**Issue by sfeister** [jasonv/MythSim#4]
I am an instructor for a Computer Organization and Architecture university course, and I'd like to use MythSim to teach my students about microcode. However, I'm hitting an issue with running it.

# Expected behavior and actual behavior.
Based on setup instructions in the User's Guide, expected to find mythsim.jar upon unzipping download of repo. Could not locate this file.

# Steps to reproduce the problem.
Go to https://github.com/jasonv/MythSim, click "Clone or Download" button, unzip the download. Inspect the directory of unzipped files.

# Specifications like the version of the project, operating system, or hardware.
Windows 10

**Comment by sfeister** [comment]
If you are still developing, perhaps compilation instructions would be helpful, too. Thanks! -Scott

**Comment by sfeister** [comment]
The User's Guide also refers to a "MythSim" site for more information, which I believe may no longer be maintained? Is there still a website outside of GitHub for MythSim? Thanks!

**Comment by jasonv** [comment]
Thank you for your interest.  I have added a runnable jar under the releases section (https://github.com/jasonv/MythSim/releases).  Let me know if you have any issues. - JasonV
